name: busrt_client
description: This is a client for the bus https://github.com/alttch/busrt.
version: 0.3.0
repository: https://github.com/AndreiLosev/busrt_client

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  future_soket: ^1.0.0
  mutex: ^3.1.0
  typed_data: ^1.3.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
